/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Programas;

import Clases.ConeccionBD;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Ruben
 */
public class ActualizarCliente extends javax.swing.JDialog {
String cedula, nombre, apellido, direccion, telefono, correo, tipo, sexo;
private ConeccionBD bd;
  private ResultSet rs;
   private boolean error;
   private Cliente cliente;
    /**
     * Creates new form ActualizarCliente
     */
    public ActualizarCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
      //  bd.estaConectado();
        traerDatos();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtcedulaactualizar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtnombreactualizar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txtapellidoactualizar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbsociosactualizar = new javax.swing.JComboBox();
        cmbsexoactualizar = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jlblErrorAgregarCI = new javax.swing.JLabel();
        jlblErrorAgregarNombres = new javax.swing.JLabel();
        jlblErrorAgregarApellido = new javax.swing.JLabel();
        txtdireccionactualizar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txttelefonoactualizar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtcorreoactualizar = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnguardar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Imagenes/icon_45.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSeparator1.setBackground(new java.awt.Color(255, 153, 0));
        jSeparator1.setForeground(new java.awt.Color(255, 153, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        txtcedulaactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcedulaactualizarActionPerformed(evt);
            }
        });
        txtcedulaactualizar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcedulaactualizarKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcedulaactualizarKeyTyped(evt);
            }
        });

        jLabel3.setText("Cedula Cliente");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setMinimumSize(new java.awt.Dimension(100, 10));

        jLabel4.setText("Nombre Cliente");

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setMinimumSize(new java.awt.Dimension(100, 10));

        jLabel5.setText("Apellido Cliente");

        cmbsociosactualizar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Socios", "No Socios" }));

        cmbsexoactualizar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Femenino" }));

        jLabel6.setText("Tipo de Cliente");

        jLabel7.setText("Sexo CLiente");

        jlblErrorAgregarCI.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlblErrorAgregarCI.setForeground(new java.awt.Color(255, 0, 0));
        jlblErrorAgregarCI.setText("* Este campo no puede dejarse en blanco");

        jlblErrorAgregarNombres.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlblErrorAgregarNombres.setForeground(new java.awt.Color(255, 0, 0));
        jlblErrorAgregarNombres.setText("*Este campo no puede dejarse en blanco");

        jlblErrorAgregarApellido.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlblErrorAgregarApellido.setForeground(new java.awt.Color(255, 0, 0));
        jlblErrorAgregarApellido.setText("*Este campo no puede dejarse en blanco");

        jLabel8.setText("Direccion");

        jLabel9.setText("Telefono");

        jLabel10.setText("Correo");

        btnguardar.setBackground(new java.awt.Color(0, 204, 204));
        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Imagenes/Save.png"))); // NOI18N
        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btncancelar.setBackground(new java.awt.Color(255, 0, 51));
        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Imagenes/Back.png"))); // NOI18N
        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        jTextField1.setBorder(javax.swing.BorderFactory.createTitledBorder("N° Socio"));
        jTextField1.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(212, 212, 212)
                                        .addComponent(jLabel2))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(165, 165, 165)
                                        .addComponent(jLabel5))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(txttelefonoactualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtnombreactualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlblErrorAgregarNombres))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel6)
                                        .addGap(93, 93, 93)
                                        .addComponent(jLabel7)
                                        .addGap(61, 61, 61))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jlblErrorAgregarApellido)
                                                        .addGap(0, 0, Short.MAX_VALUE))
                                                    .addComponent(txtapellidoactualizar)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(cmbsociosactualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(cmbsexoactualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(32, 32, 32))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnguardar)
                                        .addGap(29, 29, 29)
                                        .addComponent(btncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtcorreoactualizar, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtdireccionactualizar))
                                .addGap(32, 32, 32))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtcedulaactualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jlblErrorAgregarCI))
                                    .addComponent(jLabel10)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addContainerGap())))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtcedulaactualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                    .addComponent(jlblErrorAgregarCI, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtapellidoactualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtnombreactualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblErrorAgregarNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblErrorAgregarApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbsexoactualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbsociosactualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txttelefonoactualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtdireccionactualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcorreoactualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcedulaactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcedulaactualizarActionPerformed
        txtnombreactualizar.requestFocus();
        btnguardar.setEnabled(true);        // TODO add your handling code here:
    }//GEN-LAST:event_txtcedulaactualizarActionPerformed

    private void txtcedulaactualizarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcedulaactualizarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcedulaactualizarKeyPressed

    private void txtcedulaactualizarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcedulaactualizarKeyTyped
        //char car = evt.getKeyChar();
        //  String Caracteres1= txtcedula.getText();
        // int cara = Integer.parseInt(this.txtCedulaAgre.getText());
        // int Caracteres = Integer.parseInt(txtCedulaAgre.getText());

        //if((car<'0' || car>'9')){
            //  evt.consume();
            ////getToolkit().beep();
            //}
        char car = evt.getKeyChar();
        if(txtcedulaactualizar.getText().length()>=7) evt.consume();
        if((car<'0' || car>'9')) evt.consume();

        //if(Caracteres1.length()>7){
            // evt.consume();

            //}// TODO add your handling code here:
    }//GEN-LAST:event_txtcedulaactualizarKeyTyped

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        if (!existeCamposObligatoriosDeAgregarClienteEnBlanco()) {
            actualizar();
           
        }

    }//GEN-LAST:event_btnguardarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_btncancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActualizarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActualizarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActualizarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActualizarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ActualizarCliente dialog = new ActualizarCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JComboBox cmbsexoactualizar;
    private javax.swing.JComboBox cmbsociosactualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel jlblErrorAgregarApellido;
    private javax.swing.JLabel jlblErrorAgregarCI;
    private javax.swing.JLabel jlblErrorAgregarNombres;
    private javax.swing.JTextField txtapellidoactualizar;
    private javax.swing.JTextField txtcedulaactualizar;
    private javax.swing.JTextField txtcorreoactualizar;
    private javax.swing.JTextField txtdireccionactualizar;
    private javax.swing.JTextField txtnombreactualizar;
    private javax.swing.JTextField txttelefonoactualizar;
    // End of variables declaration//GEN-END:variables
private void traerDatos(){
////////////////trae la descripcion y codigo de la sucursal desde el acceso///////////
    cedula= Cliente.getCedula();
    txtcedulaactualizar.setText(cedula);
    txtcedulaactualizar.repaint();
    
    nombre= Cliente.getNombre();
    txtnombreactualizar.setText(nombre);
    txtnombreactualizar.repaint();
    
    apellido= Cliente.getApellido();
    txtapellidoactualizar.setText(apellido);
    txtapellidoactualizar.repaint();
    
    direccion= Cliente.getDireccion();
    txtdireccionactualizar.setText(direccion);
    txtdireccionactualizar.repaint();
    
    telefono= Cliente.getTelefono();
    txttelefonoactualizar.setText(telefono);
    txttelefonoactualizar.repaint();
    
    correo= Cliente.getCorreo();
    txtcorreoactualizar.setText(correo);
    txtcorreoactualizar.repaint();
    
    tipo= Cliente.gettipo();
    cmbsociosactualizar.setSelectedItem(tipo);
    cmbsociosactualizar.repaint();
    
    sexo= Cliente.getSexo();
    cmbsexoactualizar.setSelectedItem(sexo);
    cmbsexoactualizar.repaint();
    
    txtcedulaactualizar.setEditable(false);
    
    
    
     }
private boolean existeCamposObligatoriosDeAgregarClienteEnBlanco() {
        boolean existe = false;
        if (this.txtcedulaactualizar.getText().length() == 0) {
            this.jlblErrorAgregarCI.setVisible(true);
            existe = true;
        }
        if (this.txtnombreactualizar.getText().length() == 0) {
            this.jlblErrorAgregarNombres.setVisible(true);
            existe = true;
        }
        if (this.txtapellidoactualizar.getText().length() == 0) {
            this.jlblErrorAgregarApellido.setVisible(true);
            existe = true;
        }
        return existe;
    }
private boolean existeCedulaCliente() {
        boolean existe = false;
        if (bd.existeCedulaCliente(this.txtcedulaactualizar.getText())) {
            existe = true;
        }
        return existe;
    }
private void actualizar(){
      try {
        ConeccionBD z = new ConeccionBD();
             Connection cn = z.conectar();
             Statement stmt = cn.createStatement();
             
       String update = "UPDATE clientes " + "SET "
                        + "NombreCliente='" + txtnombreactualizar.getText() + "', "
                        + "ApellidoCliente='" + txtapellidoactualizar.getText() + "', "
                        + "DireccionCliente='" + txtdireccionactualizar.getText() + "', "
                        + "TelefonoCliente='" + txttelefonoactualizar.getText() + "', "
                        + "CorreoCliente='" + txtcorreoactualizar.getText() + "' ,"
                        + "tipoCliente='" + cmbsociosactualizar.getSelectedItem() + "' ,"
                        + "sexoCliente='" + cmbsexoactualizar.getSelectedItem()+ "' "
                        + "WHERE ci_cliente='" + txtcedulaactualizar.getText() + "';";
            JOptionPane.showMessageDialog(null, "Se ha Modificado con exito", "Felicitaciones",JOptionPane.INFORMATION_MESSAGE);
                stmt.executeUpdate(update);
                stmt.close();
                cn.close();
              } catch (SQLException ex) {
                Logger.getLogger(ActualizarCliente.class.getName()).log(Level.SEVERE, null, ex);
            }  
                        
           this.dispose();            
    }

private void ocultarAvisosDeError() {
        this.jlblErrorAgregarCI.setVisible(false);
        this.jlblErrorAgregarNombres.setVisible(false);
        this.jlblErrorAgregarApellido.setVisible(false);

    }
}
