/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Programas;

import Clases.ConeccionBD;

import Clases.Pelicula;
import com.sun.istack.internal.FinalArrayList;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.ByteArrayOutputStream;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Ruben
 */
public class CatalogoPeliculas extends javax.swing.JDialog {
private ResultSet rs, res; 
private int i;
private ConeccionBD bd;
private Pelicula Pelicula;
private AgregarEjemplar agregarejemplar;
private RegistrarAlquiler RE;
  int cont= 0;
  int contador;
  private boolean activoBuscarPorGenero;
    private boolean activoBuscarPorTitulo;
    private boolean activoVerTodosLosGeneros;
    private ArrayList<Pelicula> ListaPelicula;
    String  vtitulo, vorigen, vdirector, vactores, vsinopsis, vgenero, vduracion;
    int vcodigo, vstock;
    InputStream imagen;
   public  boolean re, ej;
    /**
     * Creates new form CatalogoPeliculas
     */
    public CatalogoPeliculas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         cmbGenero.setEnabled(false);
         
       jtxfBuscarPorTitulo.setEnabled(false);
       this.activoBuscarPorGenero = false;
        this.activoBuscarPorTitulo = false;
        this.activoVerTodosLosGeneros = true;
        ListaPelicula = new ArrayList<Pelicula>();
        bd= new ConeccionBD();
        cargaGenero();
       mostrarCatalogoPeliculasTodosLosGeneros();         
        
    }
    public void  CatalogoPeliculas(boolean reg, boolean eje){
        re= reg;
        ej= eje;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        cmbGenero = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jrbtnTitulo = new javax.swing.JRadioButton();
        jrbtnGenero = new javax.swing.JRadioButton();
        jtxfBuscarPorTitulo = new javax.swing.JTextField();
        jbtnVerPeliculas = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lblPeliculaTituloGrande = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblPeliculaTitulo = new javax.swing.JLabel();
        lblPeliculaGenero = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblPeliculaDuracion = new javax.swing.JLabel();
        lblPeliculaPais = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblPeliculaDirector = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaPeliculaActores = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaPeliculaSinopsis = new javax.swing.JTextArea();
        lblfoto = new javax.swing.JLabel();
        btnatras = new javax.swing.JButton();
        btnsiguiente = new javax.swing.JButton();
        jlblPeliculaGeneroSeleccionado = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(153, 255, 204));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 153, 0));
        jLabel20.setText("CATÁLOGO DE PELÍCULAS");

        jPanel7.setBackground(new java.awt.Color(255, 204, 0));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Buscar Por", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(255, 204, 0)));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Título:");

        cmbGenero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbGeneroMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cmbGeneroMousePressed(evt);
            }
        });
        cmbGenero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbGeneroKeyPressed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Género:");

        jrbtnTitulo.setBackground(new java.awt.Color(255, 204, 0));
        jrbtnTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jrbtnTitulo.setText("Título");
        jrbtnTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrbtnTituloMouseClicked(evt);
            }
        });
        jrbtnTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtnTituloActionPerformed(evt);
            }
        });

        jrbtnGenero.setBackground(new java.awt.Color(255, 204, 0));
        jrbtnGenero.setForeground(new java.awt.Color(255, 255, 255));
        jrbtnGenero.setText("Género");
        jrbtnGenero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrbtnGeneroMouseClicked(evt);
            }
        });

        jtxfBuscarPorTitulo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtxfBuscarPorTitulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxfBuscarPorTituloKeyPressed(evt);
            }
        });

        jbtnVerPeliculas.setBackground(new java.awt.Color(255, 255, 255));
        jbtnVerPeliculas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnVerPeliculas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Imagenes/verPelicula.png"))); // NOI18N
        jbtnVerPeliculas.setText("Ver");
        jbtnVerPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnVerPeliculasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnVerPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jrbtnGenero)
                    .addGap(2, 2, 2)
                    .addComponent(jrbtnTitulo)
                    .addGap(67, 67, 67)
                    .addComponent(jLabel12)
                    .addGap(4, 4, 4)
                    .addComponent(cmbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(39, 39, 39)
                    .addComponent(jLabel19)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jtxfBuscarPorTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 104, Short.MAX_VALUE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 21, Short.MAX_VALUE)
                .addComponent(jbtnVerPeliculas))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(5, 13, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jrbtnGenero, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jrbtnTitulo, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(cmbGenero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jtxfBuscarPorTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel4.setBackground(new java.awt.Color(255, 204, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)), "Detalle", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(255, 102, 0)));

        lblPeliculaTituloGrande.setEditable(false);
        lblPeliculaTituloGrande.setBackground(new java.awt.Color(255, 204, 0));
        lblPeliculaTituloGrande.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Título      :");

        lblPeliculaTitulo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblPeliculaTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblPeliculaTitulo.setText("Titulo");

        lblPeliculaGenero.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblPeliculaGenero.setForeground(new java.awt.Color(255, 255, 255));
        lblPeliculaGenero.setText("Género");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Género    :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Duración :");

        lblPeliculaDuracion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblPeliculaDuracion.setForeground(new java.awt.Color(255, 255, 255));
        lblPeliculaDuracion.setText("Duración");

        lblPeliculaPais.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblPeliculaPais.setForeground(new java.awt.Color(255, 255, 255));
        lblPeliculaPais.setText("País");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("País         : ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Director   :");

        lblPeliculaDirector.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblPeliculaDirector.setForeground(new java.awt.Color(255, 255, 255));
        lblPeliculaDirector.setText("Director");

        jScrollPane2.setForeground(new java.awt.Color(255, 204, 0));

        txaPeliculaActores.setColumns(20);
        txaPeliculaActores.setRows(5);
        jScrollPane2.setViewportView(txaPeliculaActores);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Actores   :");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addComponent(lblPeliculaPais, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblPeliculaTituloGrande, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(17, 17, 17)
                            .addComponent(lblPeliculaTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(17, 17, 17)
                            .addComponent(lblPeliculaGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(18, 18, 18)
                            .addComponent(lblPeliculaDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel8)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(15, 15, 15)
                            .addComponent(lblPeliculaDirector, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addGap(7, 7, 7)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(lblPeliculaPais)
                .addContainerGap(124, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblPeliculaTituloGrande, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(9, 9, 9)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(lblPeliculaTitulo))
                    .addGap(5, 5, 5)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addComponent(lblPeliculaGenero))
                    .addGap(5, 5, 5)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7)
                        .addComponent(lblPeliculaDuracion))
                    .addGap(5, 5, 5)
                    .addComponent(jLabel8)
                    .addGap(5, 5, 5)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9)
                        .addComponent(lblPeliculaDirector))
                    .addGap(5, 5, 5)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel10)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 20, Short.MAX_VALUE)))
        );

        jPanel2.setBackground(new java.awt.Color(255, 204, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)), "Sinopsis", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(255, 102, 0)));

        txaPeliculaSinopsis.setColumns(20);
        txaPeliculaSinopsis.setRows(5);
        jScrollPane1.setViewportView(txaPeliculaSinopsis);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(25, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(30, 30, 30)))
        );

        lblfoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Imagenes/Dibujo.JPG"))); // NOI18N

        btnatras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Imagenes/atras.png"))); // NOI18N
        btnatras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnatrasActionPerformed(evt);
            }
        });

        btnsiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Imagenes/siguiente.png"))); // NOI18N
        btnsiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsiguienteActionPerformed(evt);
            }
        });

        jlblPeliculaGeneroSeleccionado.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblPeliculaGeneroSeleccionado.setText("TODOS LOS GÉNEROS");

        jButton1.setBackground(new java.awt.Color(255, 153, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("SALIR O CAPTURAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblfoto, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(btnatras, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(151, 151, 151)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnsiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jlblPeliculaGeneroSeleccionado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel20)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jlblPeliculaGeneroSeleccionado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnatras, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnsiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(34, 34, 34))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbtnTituloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrbtnTituloMouseClicked
        cmbGenero.setEnabled(false);
        this.activoBuscarPorGenero = false;
        jrbtnGenero.setSelected(false);
        this.jlblPeliculaGeneroSeleccionado.setText("BUSQUEDA DE PELICULA POR TITULO");
            

        this.activoBuscarPorTitulo = true;
        this.jtxfBuscarPorTitulo.setEnabled(true);

    }//GEN-LAST:event_jrbtnTituloMouseClicked

    private void jrbtnGeneroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrbtnGeneroMouseClicked
        this.jtxfBuscarPorTitulo.setEnabled(false);
        this.jtxfBuscarPorTitulo.setText("");
         this.activoBuscarPorTitulo = false;
         jrbtnTitulo.setSelected(false);
         this.jlblPeliculaGeneroSeleccionado.setText("BUSQUEDA DE PELICULA POR GENERO");
       
       // System.out.println("activoGenero=" + this.activoBuscarPorGenero);
        this.cmbGenero.setEnabled(true);
        this.activoBuscarPorGenero=true;
    }//GEN-LAST:event_jrbtnGeneroMouseClicked

    private void btnatrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnatrasActionPerformed
if (i > 0) {
            i--;
            if (this.activoVerTodosLosGeneros) {
                mostrarCatalogoPeliculasTodosLosGeneros();
            } else {
                mostrarCatalogoPeliculasPorGenero();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Llego al inicio del catálogo.\n No hay más Películas");

        }
// TODO add your handling code here:
    }//GEN-LAST:event_btnatrasActionPerformed

    private void btnsiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsiguienteActionPerformed
 if (i < (this.ListaPelicula.size() - 1)) {
            i++;
            if (this.activoVerTodosLosGeneros) {
                mostrarCatalogoPeliculasTodosLosGeneros();
            } else {
                mostrarCatalogoPeliculasPorGenero();
            }
        } else {
            JOptionPane.showMessageDialog(this, "LLego al final del catálogo.\n No hay más Peliculas");
        }

// TODO add your handling code here:
    }//GEN-LAST:event_btnsiguienteActionPerformed

    private void cmbGeneroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbGeneroMouseClicked

// TODO add your handling code here:
    }//GEN-LAST:event_cmbGeneroMouseClicked

    private void cmbGeneroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbGeneroMousePressed
       // TODO add your handling code here:
    }//GEN-LAST:event_cmbGeneroMousePressed

    private void cmbGeneroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbGeneroKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbGeneroKeyPressed

    private void jbtnVerPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnVerPeliculasActionPerformed
        if (activoBuscarPorGenero) {
            this.activoVerTodosLosGeneros = false;
            this.jlblPeliculaGeneroSeleccionado.setText("GENERO '"+cmbGenero.getSelectedItem()+"'");
            
            mostrarCatalogoPeliculasPorGenero();
            
            
        }
        if (activoBuscarPorTitulo) {
           
            BuscarPorTitulo();
             this.jlblPeliculaGeneroSeleccionado.setText("BUSQUEDA RELACIONADA A  '"+jtxfBuscarPorTitulo.getText()+"'");
            jrbtnGenero.setSelected(false);
            
            
        }
    }//GEN-LAST:event_jbtnVerPeliculasActionPerformed

    private void jtxfBuscarPorTituloKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxfBuscarPorTituloKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxfBuscarPorTituloKeyPressed

    private void jrbtnTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtnTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbtnTituloActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

 System.out.println(re);
System.out.println(ej);  
if (re==true){
     RE.txttitulo.setText(Pelicula.getTitulo());
    RE.txttitulo.requestFocus();
   
     this.dispose();
}else{
    if(ej==true){
        agregarejemplar.txtPeliculaTitulo.setText(Pelicula.getTitulo());   
    agregarejemplar.txtPeliculaTitulo.requestFocus();
    this.dispose();
    }else{
        this.dispose();
    }
    
}

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CatalogoPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CatalogoPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CatalogoPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CatalogoPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               CatalogoPeliculas dialog = new CatalogoPeliculas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                   }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnatras;
    private javax.swing.JButton btnsiguiente;
    private javax.swing.JComboBox cmbGenero;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtnVerPeliculas;
    private javax.swing.JLabel jlblPeliculaGeneroSeleccionado;
    private javax.swing.JRadioButton jrbtnGenero;
    private javax.swing.JRadioButton jrbtnTitulo;
    private javax.swing.JTextField jtxfBuscarPorTitulo;
    private javax.swing.JLabel lblPeliculaDirector;
    private javax.swing.JLabel lblPeliculaDuracion;
    private javax.swing.JLabel lblPeliculaGenero;
    private javax.swing.JLabel lblPeliculaPais;
    private javax.swing.JLabel lblPeliculaTitulo;
    private javax.swing.JTextField lblPeliculaTituloGrande;
    private javax.swing.JLabel lblfoto;
    private javax.swing.JTextArea txaPeliculaActores;
    private javax.swing.JTextArea txaPeliculaSinopsis;
    // End of variables declaration//GEN-END:variables

private void cargaGenero(){
          ConeccionBD z = new ConeccionBD();
            Connection cn = z.conectar();
        try {
            String sql = "SELECT * FROM genero order by idGenero ";
                Statement st = cn.createStatement();
                rs = st.executeQuery(sql);
                cmbGenero.removeAllItems();
                while (rs.next()) {
                    cmbGenero.addItem(rs.getString("DescripcionGenero"));
    }
    
        } catch (SQLException ex) {
            Logger.getLogger(AgregarPelicula.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

 
private void BuscarPorTitulo(){
    
        ConeccionBD z = new ConeccionBD();
            Connection cn = z.conectar();
            try {
            Statement st = cn.createStatement();
            String sql = "SELECT *FROM vpeliculas where concat(Titulo) like'%"+jtxfBuscarPorTitulo.getText()+"%'";
                rs = st.executeQuery(sql);
                while (rs.next()) {
                    String Codigo = rs.getString("Codigo");
                    System.out.println( Codigo);
                    String titulo = rs.getString("Titulo");
                    System.out.println( titulo);
                    String duracion = rs.getString("Duracion");
                    String pais = rs.getString("Pais");
                    String director = rs.getString("Director");
                    String actores = rs.getString("Actores");
                    String sinopsis = rs.getString("Sinopsis");
                    String idGenero = rs.getString("Genero");
                    String stock = rs.getString("Stock");
                    InputStream imagen= rs.getBinaryStream("Foto");
         
            lblPeliculaTituloGrande.setText(titulo);
            lblPeliculaTitulo.setText(titulo);
           lblPeliculaDuracion.setText(duracion);
           lblPeliculaGenero.setText(idGenero);
           lblPeliculaPais.setText(pais);
           lblPeliculaDirector.setText(director);
           txaPeliculaActores.setText(actores);
           txaPeliculaSinopsis.setText(sinopsis);
           if (imagen!=null){
           Image icono = ImageIO.read(imagen).getScaledInstance(lblfoto.getWidth(),
                    lblfoto.getHeight(), Image.SCALE_DEFAULT);
                   lblfoto.setIcon(new ImageIcon(icono));
                   lblfoto.updateUI();
       
           
        
        
               
    }else {
        this.lblfoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Imagenes/Dibujo.jpg")));
    }

                   
                }


                   


            } catch (IOException ex) {
            Logger.getLogger(CatalogoPeliculas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
}

  private void mostrarCatalogoPeliculasPorGenero() {
 
        ListaPelicula = BusquedaPorGenero();
      
        if (ListaPelicula != null) {
            if (ListaPelicula.size() != 0) {
                 Pelicula = ListaPelicula.get(i);
      
                this.lblPeliculaTituloGrande.setText(this.Pelicula.getTitulo());
                this.lblPeliculaTitulo.setText(this.Pelicula.getTitulo());
                this.lblPeliculaGenero.setText(this.Pelicula.getGenero());
                this.lblPeliculaDuracion.setText(this.Pelicula.getDuracion());
                this.lblPeliculaPais.setText(this.Pelicula.getPais());
                this.lblPeliculaDirector.setText(this.Pelicula.getDirector());
                this.txaPeliculaActores.setText(this.Pelicula.getActores());
                this.txaPeliculaSinopsis.setText(this.Pelicula.getSinopsis());
                imagen= this.Pelicula.getImagen();
           if (imagen!=null){
        try {
           Image icono = ImageIO.read(imagen).getScaledInstance(lblfoto.getWidth(),
                    lblfoto.getHeight(), Image.SCALE_DEFAULT);
                   lblfoto.setIcon(new ImageIcon(icono));
                   lblfoto.updateUI();
        } catch (IOException ex) {
            Logger.getLogger(ActualizarPelicula.class.getName()).log(Level.SEVERE, null, ex);
        
            }
        }
    }
}
}
  private void mostrarCatalogoPeliculasTodosLosGeneros( ) {
        this.ListaPelicula = verDatos();
        if (ListaPelicula != null) {
            if (ListaPelicula.size() != 0) {
                Pelicula = ListaPelicula.get(i);
                this.lblPeliculaTituloGrande.setText(this.Pelicula.getTitulo());
                this.lblPeliculaTitulo.setText(this.Pelicula.getTitulo());
                this.lblPeliculaGenero.setText(this.Pelicula.getGenero());
                this.lblPeliculaDuracion.setText(this.Pelicula.getDuracion());
                this.lblPeliculaPais.setText(this.Pelicula.getPais());
                this.lblPeliculaDirector.setText(this.Pelicula.getDirector());
                this.txaPeliculaActores.setText(this.Pelicula.getActores());
                this.txaPeliculaSinopsis.setText(this.Pelicula.getSinopsis());
                imagen= this.Pelicula.getImagen();
                
                 if (imagen!=null){
           Image icono;
                    try {
                        icono = ImageIO.read(imagen).getScaledInstance(lblfoto.getWidth(),
                           lblfoto.getHeight(), Image.SCALE_DEFAULT);
                         lblfoto.setIcon(new ImageIcon(icono));
                        lblfoto.updateUI();
                    } catch (IOException ex) {
                        Logger.getLogger(CatalogoPeliculas.class.getName()).log(Level.SEVERE, null, ex);
                    }
                  
       
           
        
        
               
    }else {
        this.lblfoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Imagenes/Dibujo.jpg")));
    }
            }
        }
    }
  private void GenerarCodigoGenero(){
      ConeccionBD z = new ConeccionBD();
            Connection cn = z.conectar();
            
            String sqls= "Select count(*) cantidad from vpeliculas where Genero = '"+cmbGenero.getSelectedItem()+"'";
            Statement stmt;
        try {
            stmt = cn.createStatement();
             res= stmt.executeQuery(sqls);
            res.next();
            contador= res.getInt("cantidad");
            System.out.print(contador);
        } catch (SQLException ex) {
            Logger.getLogger(CatalogoPeliculas.class.getName()).log(Level.SEVERE, null, ex);
        }
  }
    public  ArrayList<Pelicula> BusquedaPorGenero(){
    ListaPelicula.clear();
        ConeccionBD z = new ConeccionBD();
            Connection cn = z.conectar();
           int i= 0;
            String sql = "SELECT *FROM vpeliculas WHERE Genero ='"+cmbGenero.getSelectedItem()+"'";
            try {
                Statement st = cn.createStatement();
                rs = st.executeQuery(sql);
                while (rs.next()) {
                    
                    int vcodigo = rs.getInt("Codigo");
                    String vtitulo = rs.getString("Titulo");
                    String vduracion = rs.getString("Duracion");
                    String vorigen = rs.getString("Pais");
                    String vdirector = rs.getString("Director");
                   String  vactores = rs.getString("Actores");
                   String  vsinopsis = rs.getString("Sinopsis");
                   String  vgenero = rs.getString("Genero");
                   int   vstock = rs.getInt("Stock");
                   InputStream imagen= rs.getBinaryStream("Foto");
                    Pelicula= new Pelicula(vcodigo, vtitulo,vduracion, vorigen, vdirector, vactores, vsinopsis, vgenero, vstock, imagen);
                     ListaPelicula.add(i, Pelicula);   
                     i++;
                }

            } catch (SQLException ex) {
            Logger.getLogger(CatalogoPeliculas.class.getName()).log(Level.SEVERE, null, ex);
        }
            return ListaPelicula;
      }   
    public ArrayList<Pelicula>  verDatos(){
     ListaPelicula.clear();
     int i=0;
        ConeccionBD z = new ConeccionBD();
            Connection cn = z.conectar();
            String sql = "SELECT *FROM vpeliculas ";
            try {
                Statement st = cn.createStatement();
                rs = st.executeQuery(sql);
                while (rs.next()) {
                    
                    int Codigo = rs.getInt("Codigo");
                    String titulo = rs.getString("Titulo");
                    String duracion = rs.getString("Duracion");
                    String pais = rs.getString("Pais");
                    String director = rs.getString("Director");
                    String actores = rs.getString("Actores");
                    String sinopsis = rs.getString("Sinopsis");
                    String Genero = rs.getString("Genero");
                    int stock = rs.getInt("Stock");
                    InputStream imagen= rs.getBinaryStream("Foto");
   Pelicula= new Pelicula(Codigo, titulo,duracion, pais, director, actores, sinopsis, Genero, stock, imagen);
                     ListaPelicula.add(i, Pelicula);   
                     i++;
           
              }


                   


            } catch (SQLException ex) {
            Logger.getLogger(CatalogoPeliculas.class.getName()).log(Level.SEVERE, null, ex);
        }
            return ListaPelicula;
      }
}
 

